name: test

on:
  push:
    branches:                  
      - master
  pull_request:

permissions:                   
  contents: read               

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: php-8.1
            os: ubuntu-latest
            php-version: '8.1'
          - name: php-8.2
            os: ubuntu-latest
            php-version: '8.2'
          - name: php-8.3
            os: ubuntu-latest
            php-version: '8.3'
          - name: php-8.4
            os: ubuntu-latest
            php-version: '8.4'
          - name: ubuntu-latest
            os: ubuntu-latest
    steps:
      - if: ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: phpcs
        run: ./vendor/bin/phpcs -n --standard=PSR2 src/ tests/

      - name: PHP version
        run: php -v

      - name: tests
        run: php ./tests/HJSONParserTest.php
